apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-api-configmap
  namespace: fast-order
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5000"
  DB_CONNECTION_STRING: "Server=rds-fastorderdb-tf.c3qig4kemrm8.us-east-1.rds.amazonaws.com,1433;Database=PedidosDB;User Id=sa;Password=tech#2024;Encrypt=false;TrustServerCertificate=true;MultipleActiveResultSets=true;"
  DISTRIBUTED_CACHE_URL: "soat-cache.uwgp5c.ng.0001.use1.cache.amazonaws.com:6379"
  RUN_MIGRATIONS_ON_START: "true"
  PAGAMENTO_WEB_API_URL: "http://a6d6ea7fcad5549d9947adc6d92d86fe-2059151732.us-east-1.elb.amazonaws.com"