apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-dep
  namespace: fast-order
  labels:
    app: pedidos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos-api
  template:
    metadata:
      labels:
        app: pedidos-api
    spec:
      containers:
      - name: pedidos-api-cont
        image: sickbanger/pedidos-api:latest
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: pedidos-api-configmap
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
