apiVersion: v1
kind: Service
metadata:
  name: pedidos-api-svc
  namespace: fast-order
spec:
  selector:
    app: pedidos-api
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 5000
    - port: 443
      name: https
      targetPort: 5000
