name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - name: Restore dependencies
        run: dotnet restore src/Pedidos.Api/Pedidos.Api.csproj

      - name: Build and publish
        run: |
              dotnet build src/Pedidos.Api/Pedidos.Api.csproj -c Release --no-restore
              dotnet publish src/Pedidos.Api/Pedidos.Api.csproj -c Release -o app/publish /p:UseAppHost=false
              
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Ensure certs folder exists
        run: mkdir -p certs

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pedidos-api:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/pedidos-api:${{ github.sha }} \
            .
      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pedidos-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/pedidos-api:${{ github.sha }}
